apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: h3c5v2g2p-python 
  janus-idp.io/tekton: h3c5v2g2p-python
  backstage.io/kubernetes-id: h3c5v2g2p-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: h3c5v2g2p-python
resources:
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml