apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: h3c5v2g2p-python
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: h3c5v2g2p-python 
  name: h3c5v2g2p-python
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: h3c5v2g2p-python 
